apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy-express
  name: deploy-express
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy-express
  template:
    metadata:
      labels:
        app: deploy-express
    spec:
      containers:
      - image: nginx
        name: express-app
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m # i.e 0.2 core of cpu
          limits:
            cpu: 500m 

