apiVersion: v1
data:
  Name: RGV2
kind: Secret
metadata:
  creationTimestamp: "2025-07-27T04:52:37Z"
  name: demo-secret
  namespace: default
  resourceVersion: "664"
  uid: e12eeaae-31b4-4291-83ee-24433e4d1fcc
type: Opaque
