apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy-express
  name: deploy-express
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy-express
  template:
    metadata:
      labels:
        app: deploy-express
    spec:
      containers:
      - image: devnishant063/express-app:3.0
        name: express-app
        env:
        - name: APP_NAME
          value: "express-demo"
        ports:
        - containerPort: 3000
