apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deploy-express
  name: service-express
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
    nodePort: 30080
  selector:
    app: deploy-express
  type: NodePort