k create secret generic demo-secret --from-literal=password=hellopass

k get secret demo-secret -o yaml
echo "fff" | base64 -d

    env:
    - name: PASSWORD
    valueFrom:
      secretKeyRef:
        name: demo-secret
        key: password
        
kubectl create secret docker-registry sample-docker-secret \
--docker-email=piyush.sachdeva055@gmail.com \
--docker-username=piyushsachdeva \
--docker-password=dckr_pat_koBbtsz9m2noLFiLBMaasGjsmcQ \
--docker-server=https://index.docker.io/v2/



    imagePullPolicy: Always
    imagePullSecrets:
    - name: sample-docker-secret
    