apiVersion: v1
kind: Pod
metadata:
  name: stress-test
  labels:
    app.kubernetes.io/name: stress-test
spec:
  containers:
  - name: stress-test
    image: polinux/stress
    command: ["stress"]
    args: ["--vm","1","--vm-bytes","80M","--timeout","10s"]
    resources:
      requests:
        memory: "50Mi"
      limits:
        memory: "100Mi"
